import type { PolicySpec, Tab } from './types';

export const POLICIES: PolicySpec[] = [
  { id:'rate_up', label:'Rate +50bp', tab:'Monetary', description:'Raise the policy rate to cool demand, inflation and FX pressure.', tradeoff:'Slower credit, housing and investment.', capacityCost:14, politicalCost:0, cooldown:1, duration:4, effects:{inflation:-.006,growth:-.004,unemployment:.002,fx:-.018,credit:-.018,confidence:-.01}, transmissionEffects:{credit:-.018,confidence:-.01}},
  { id:'rate_down', label:'Rate −50bp', tab:'Monetary', description:'Lower the policy rate to support credit and demand.', tradeoff:'Can add inflation and currency pressure.', capacityCost:14, politicalCost:0, cooldown:1, duration:4, effects:{inflation:.005,growth:.005,unemployment:-.002,fx:.018,credit:.020,confidence:.012}, transmissionEffects:{credit:.020,confidence:.012}},
  { id:'reserve_up', label:'Reserve +2%', tab:'Monetary', description:'Tighten bank reserve requirements.', tradeoff:'Reduces credit availability.', capacityCost:12, politicalCost:0, cooldown:2, duration:3, effects:{credit:-.025,inflation:-.003,growth:-.002,bank:.008}},
  { id:'reserve_down', label:'Reserve −2%', tab:'Monetary', description:'Release bank liquidity.', tradeoff:'Supports activity but can increase leverage.', capacityCost:12, politicalCost:0, cooldown:2, duration:3, effects:{credit:.028,growth:.003,inflation:.002,bank:-.006}},
  { id:'qe', label:'Liquidity / QE', tab:'Monetary', description:'Inject market liquidity and compress financial stress.', tradeoff:'Inflation and FX risk if used in a strong economy.', capacityCost:24, politicalCost:2, cooldown:3, duration:5, effects:{credit:.035,growth:.004,inflation:.004,bank:.025,fx:.015}},
  { id:'bank_recap', label:'Bank Recap', tab:'Monetary', description:'Recapitalize fragile banks and restore intermediation.', tradeoff:'Uses public balance-sheet capacity.', capacityCost:22, politicalCost:4, cooldown:4, duration:4, effects:{bank:.08,credit:.025,debt:.008,treasury:-8,confidence:.03}, transmissionEffects:{bank:.08,credit:.025,treasury:-8,confidence:.03}},
  { id:'support_fx', label:'FX Defense', tab:'Monetary', description:'Use reserves and liquidity tools to stabilize the currency.', tradeoff:'Costs reserves and can tighten conditions.', capacityCost:16, politicalCost:2, cooldown:2, duration:3, effects:{fx:-.05,inflation:-.003,growth:-.001,treasury:-3}, transmissionEffects:{fx:-.05,treasury:-3}},
  { id:'macroprudential', label:'Macroprudential +', tab:'Monetary', description:'Reduce risky lending without a broad rate increase.', tradeoff:'Cools housing and credit-sensitive sectors.', capacityCost:16, politicalCost:2, cooldown:2, duration:4, effects:{credit:-.016,bank:.022,housingSupply:.002,inflation:-.001}},

  { id:'stimulus', label:'Fiscal Stimulus', tab:'Fiscal', description:'Temporary public spending and transfers to lift demand.', tradeoff:'Higher inflation and debt if the economy is near capacity.', capacityCost:28, politicalCost:7, cooldown:3, duration:5, effects:{growth:.008,unemployment:-.004,inflation:.006,debt:.018,approval:.025,treasury:-12}, transmissionEffects:{treasury:-12,confidence:.012}},
  { id:'austerity', label:'Fiscal Repair', tab:'Fiscal', description:'Reduce the primary deficit and rebuild fiscal credibility.', tradeoff:'Short-run growth and approval weaken.', capacityCost:26, politicalCost:8, cooldown:4, duration:6, effects:{growth:-.005,unemployment:.003,inflation:-.004,debt:-.028,approval:-.025,treasury:10,confidence:.015}, transmissionEffects:{treasury:10,confidence:.015}},
  { id:'income_tax_up', label:'Income Tax +', tab:'Fiscal', description:'Raise household tax revenue.', tradeoff:'Reduces disposable income.', capacityCost:18, politicalCost:5, cooldown:3, duration:5, effects:{growth:-.003,inflation:-.001,debt:-.014,treasury:8,approval:-.025}},
  { id:'income_tax_down', label:'Income Tax −', tab:'Fiscal', description:'Cut household taxes to support consumption.', tradeoff:'Worsens the fiscal balance.', capacityCost:18, politicalCost:5, cooldown:3, duration:5, effects:{growth:.004,inflation:.003,debt:.014,treasury:-8,approval:.02}},
  { id:'welfare_up', label:'Welfare +', tab:'Fiscal', description:'Increase targeted household support.', tradeoff:'Fiscal cost and possible demand pressure.', capacityCost:20, politicalCost:5, cooldown:3, duration:5, effects:{poverty:-.018,inequality:-.012,approval:.03,growth:.002,debt:.010,treasury:-6}},
  { id:'infra_up', label:'Infrastructure', tab:'Fiscal', description:'Invest in transport, utilities and productive capacity.', tradeoff:'Expensive and slow, but raises potential output.', capacityCost:24, politicalCost:6, cooldown:4, duration:8, effects:{growth:.005,tech:.8,housingSupply:.012,debt:.012,treasury:-9,confidence:.018}},
  { id:'sme_credit', label:'SME Credit', tab:'Fiscal', description:'Guarantee working-capital credit for small firms.', tradeoff:'Adds contingent fiscal and banking risk.', capacityCost:20, politicalCost:5, cooldown:3, duration:5, effects:{growth:.004,unemployment:-.003,credit:.018,debt:.006,bank:-.004}},

  { id:'education_up', label:'Education Reform', tab:'Structural', description:'Raise skills and long-run productivity.', tradeoff:'Returns arrive slowly.', capacityCost:24, politicalCost:6, cooldown:4, duration:10, effects:{tech:1.6,growth:.002,debt:.006,treasury:-5,inequality:-.004}},
  { id:'research_grant', label:'R&D Grants', tab:'Structural', description:'Support innovation, startups and technology adoption.', tradeoff:'Some projects fail and fiscal returns are delayed.', capacityCost:22, politicalCost:5, cooldown:4, duration:8, effects:{tech:2.0,growth:.003,debt:.005,treasury:-4,confidence:.018}},
  { id:'anti_corruption', label:'Anti-Corruption', tab:'Structural', description:'Improve institutions, procurement and investor confidence.', tradeoff:'High political resistance.', capacityCost:30, politicalCost:10, cooldown:6, duration:10, effects:{corruption:-.035,confidence:.035,growth:.002,debt:-.004,approval:.015}},
  { id:'business_reform', label:'Business Reform', tab:'Structural', description:'Lower regulatory frictions and improve firm entry.', tradeoff:'Transition costs for protected incumbents.', capacityCost:26, politicalCost:9, cooldown:5, duration:8, effects:{growth:.004,tech:.9,confidence:.04,unemployment:-.002}},
  { id:'public_transport', label:'Public Transit', tab:'Structural', description:'Reduce congestion and household transport costs.', tradeoff:'Requires upfront public investment.', capacityCost:22, politicalCost:5, cooldown:4, duration:8, effects:{growth:.002,emissions:-4,approval:.018,debt:.006,treasury:-5}},
  { id:'health_up', label:'Health Capacity', tab:'Structural', description:'Improve health capacity and labor resilience.', tradeoff:'Persistent fiscal cost.', capacityCost:22, politicalCost:5, cooldown:4, duration:8, effects:{growth:.001,approval:.018,poverty:-.006,debt:.006,treasury:-5}},

  { id:'tariff_up', label:'Tariffs +', tab:'Trade', description:'Protect domestic sectors with higher tariffs.', tradeoff:'Raises input costs and retaliation risk.', capacityCost:18, politicalCost:5, cooldown:3, duration:5, effects:{inflation:.004,growth:-.001,confidence:-.01}},
  { id:'tariff_down', label:'Tariffs −', tab:'Trade', description:'Open imported inputs and lower trade frictions.', tradeoff:'Protected industries face more competition.', capacityCost:16, politicalCost:3, cooldown:3, duration:5, effects:{inflation:-.003,growth:.002,confidence:.012}},
  { id:'export_support', label:'Export Support', tab:'Trade', description:'Credit and logistics support for exporters.', tradeoff:'Fiscal cost and possible misallocation.', capacityCost:20, politicalCost:4, cooldown:3, duration:6, effects:{growth:.004,fx:-.012,debt:.004,treasury:-3,confidence:.012}},
  { id:'port_upgrade', label:'Port Upgrade', tab:'Trade', description:'Expand trade infrastructure and supply-chain resilience.', tradeoff:'Capital intensive.', capacityCost:24, politicalCost:6, cooldown:4, duration:9, effects:{growth:.003,tech:.7,debt:.006,treasury:-5,confidence:.02}},
  { id:'fdi_incentives', label:'FDI Incentives', tab:'Trade', description:'Attract foreign capital and technology.', tradeoff:'Tax expenditures and exposure to external flows.', capacityCost:22, politicalCost:6, cooldown:4, duration:7, effects:{growth:.003,tech:1.1,fx:-.018,confidence:.025,debt:.004}},
  { id:'devalue', label:'Managed Devalue', tab:'Trade', description:'Improve competitiveness through a weaker currency.', tradeoff:'Raises import prices and inflation.', capacityCost:24, politicalCost:7, cooldown:4, duration:4, effects:{fx:.08,inflation:.009,growth:.003,approval:-.018}},

  { id:'food_subsidy', label:'Food Subsidy', tab:'Emergency', description:'Temporarily shield households from food-price shocks.', tradeoff:'Fiscal cost and weaker price signals.', capacityCost:18, politicalCost:4, cooldown:3, duration:4, effects:{inflation:-.004,poverty:-.012,approval:.022,debt:.007,treasury:-5}},
  { id:'energy_subsidy', label:'Energy Relief', tab:'Emergency', description:'Temporary relief from energy-price pressure.', tradeoff:'Expensive and can weaken conservation incentives.', capacityCost:18, politicalCost:5, cooldown:3, duration:4, effects:{inflation:-.004,growth:.002,approval:.018,debt:.008,treasury:-6,emissions:2}},
  { id:'housing_support', label:'Housing Supply', tab:'Emergency', description:'Accelerate housing supply and targeted support.', tradeoff:'Construction takes time and costs money.', capacityCost:22, politicalCost:5, cooldown:4, duration:7, effects:{housingSupply:.024,approval:.018,poverty:-.005,debt:.006,treasury:-5}},
  { id:'food_reserve', label:'Food Reserve', tab:'Emergency', description:'Release strategic food reserves during supply stress.', tradeoff:'Finite reserve capacity.', capacityCost:16, politicalCost:4, cooldown:4, duration:3, effects:{inflation:-.005,approval:.014,treasury:-3}},
  { id:'imf_bailout', label:'External Program', tab:'Emergency', description:'Emergency external financing plus stabilization conditions.', tradeoff:'Political cost and tighter fiscal conditions.', capacityCost:35, politicalCost:14, cooldown:8, duration:8, effects:{debt:-.045,fx:-.07,bank:.06,treasury:18,growth:-.004,approval:-.04,confidence:.05}}
];

export const TABS: Tab[] = ['Monetary','Fiscal','Structural','Trade','Emergency','Advisor'];
export const policiesByTab = (tab: Tab) => POLICIES.filter(p => p.tab === tab);
export const policyById = (id: string) => POLICIES.find(p => p.id === id);
