import { useState, type ChangeEvent } from 'react';
import type { EconomySnapshot, GameMode } from '../game/types';

export type V9Setup={
  difficulty:'Learning'|'Standard'|'Expert';
};

export default function StartScreenV9({hasSave,econ,onContinue,onStart}:{hasSave:boolean;econ:EconomySnapshot;onContinue:()=>void;onStart:(mode:GameMode,setup:V9Setup)=>void}){
  const [mode,setMode]=useState<GameMode>('mission');
  const [difficulty,setDifficulty]=useState<V9Setup['difficulty']>('Standard');
  return <div className="v10-start-screen">
    <div className="v10-start-shell">
      <section className="v10-start-hero">
        <div className="v10-start-logo">M</div>
        <span className="eyebrow">LIVE ECONOMY SIMULATION</span>
        <h1>MACROSTATE</h1>
        <p>Manage a living economy. The game starts balanced; shocks, political pressure, banking stress and inflation surprises emerge dynamically inside play.</p>
        <div className="hero-metrics">
          <Preview label="Growth" value={`${(econ.growth*100).toFixed(1)}%`} />
          <Preview label="Inflation" value={`${(econ.inflation*100).toFixed(1)}%`} />
          <Preview label="Unemployment" value={`${(econ.unemployment*100).toFixed(1)}%`} />
          <Preview label="Bank health" value={`${(econ.bankHealth*100).toFixed(0)}`} />
        </div>
        <div className="hero-loop"><span>Diagnose</span><i>•</i><span>Decide</span><i>•</i><span>Advance</span><i>•</i><span>React</span><i>•</i><span>Learn</span></div>
        {hasSave && <button className="continue-v10" onClick={onContinue}>Continue saved simulation</button>}
      </section>
      <section className="v10-setup-card">
        <header>
          <span className="eyebrow">START SIMULATION</span>
          <h2>Launch a dynamic economy</h2>
        </header>
        <div className="start-note">
          <b>No pre-built scenario</b>
          <span>The economy opens in a relatively balanced state. Shocks and policy dilemmas are generated by the simulation itself as you play.</span>
        </div>
        <div className="setup-row single-row">
          <div>
            <label>Game mode</label>
            <div className="pill-set">
              <button className={mode==='mission'?'active':''} onClick={()=>setMode('mission')}>Guided campaign</button>
              <button className={mode==='sandbox'?'active':''} onClick={()=>setMode('sandbox')}>Open sandbox</button>
            </div>
          </div>
          <div>
            <label>Difficulty</label>
            <select value={difficulty} onChange={(e:ChangeEvent<HTMLSelectElement>)=>setDifficulty(e.target.value as V9Setup['difficulty'])}>
              <option>Learning</option>
              <option>Standard</option>
              <option>Expert</option>
            </select>
          </div>
        </div>
        <div className="start-note emphasis">
          <b>What makes it dynamic?</b>
          <span>Bank stress, external pressure, inflation surprises, wage drift, debt problems and positive opportunities are triggered endogenously during play and force a response.</span>
        </div>
        <button className="enter-command" onClick={()=>onStart(mode,{difficulty})}>Enter policy dashboard</button>
      </section>
    </div>
  </div>
}

function Preview({label,value}:{label:string;value:string}){return <div><span>{label}</span><b>{value}</b></div>}
